server:
  port: '8081'

spring:
  jpa:
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    open-in-view: 'false'
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres