server:
  port: '8081'

spring:
  jpa:
    generate-ddl: 'false'
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    open-in-view: 'false'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres

  flyway:
    baseline-on-migrate: true
    location: classpath:/db/migration
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    enabled: true


